### ISSUE TITLE
Proof of chapter 4

### ISSUE THREAD

**Issue by gzorlee** [jezgillen/JaynesProbabilityTheory#1]
Sorry to raise an issue but it is the only way I found to communicate with you and your work is awesome!

Just a minor thing but at the beginning of proof of 4.1 aren't you supposing the case is true and arrive the conclusion it is true. If you want to start an induction shouldn't we prove it works for the case with 2 datasets instead of supposing it is true to show it is true? It is really just maybe the first 10 lines.

Again thank you again for the work and beautiful proofs. Sorry if I didn't get what you intended to do.

**Comment by jezgillen** [comment]
Hi, no problem. Thanks for taking the time to contribute. Feel free to make issues or even make a pull request if you want to add improvements. Almost all of the work on this repo was done by @MaksimIM, he should get all the credit for the great quality of his proofs. I'm glad you've found them useful! 
There's a reddit group at [https://www.reddit.com/r/jaynesprobability/](https://www.reddit.com/r/jaynesprobability/), and a discord group at https://discord.gg/mCZ6Nyrm if you are interested in joining. I haven't been very active in the group recently, but hopefully I'll get back to it soon. The discord group is still active and still has people working through the book together! You can ask questions there and they will probably get answered.

I just had a look at 4.1. The first part of the proof (on the first half of pg. 1) demonstrates that *if* the statement is true for 2 datasets, then it must be true for n datasets. You are right that it doesn't demonstrate yet that the statement *is* true for 2 datasets. But the next part of the proof (pages 2-5) is proving that the statement *is* true for 2 datasets.
The order of this proof is maybe the opposite of what you were expecting? Or have I misinterpreted your question?
(I haven't gone through the second part of the proof in much detail because it's long and I'm not great at linear algebra yet so it'll take me a while).
If you want to make an edit to make it more clear, or make the proof simpler, feel free to make a pull request. Or join the discord to discuss it!

**Comment by gzorlee** [comment]
Thank you very much for the answer to MaksimIM for his proof. I think I was more not understanding the proof. I am going to read it again with this in mind.

Just had a look at the reddit. It is great. I will definitely join the discord. Thank you for pointing them out.

**Comment by MaksimIM** [comment]
Late to the party, but better than never, they say.

Thanks for the kind words about the proofs. I think possibly they -- and certainly the exposition -- can be improved. So I can only repeat "If you want to make an edit to make it more clear, or make the proof simpler, feel free to make a pull request. Or join the discord to discuss it!". 

On this particular issue my understanding is that @jezgillen interpreted it correctly. In this proof the m=2 (m is the number of datasets, n is the number of hypothesis) is the harder thing to prove, and it implies the result for all other m rather simply -- this is what I argue in the "first ten lines" (this is not an induction per se, but a direct implication, like if you have a set where any pair of elements are equal then all elements are equal). However, proving the m=2 case is more involved, and  involves first proving the case of 3 hypothesis (n=3) and then deducing the case of arbitrary number of hypothesis (again, not by induction, but by a direct argument). It is not very technically difficult (all of linear algebra is 2D, and can actually be avoided altogether and replaced with a couple of reasonably short calculations), but has a few moving parts and is involved in that sense. I'd be glad if someone else reads it to make sure I did not make a careless mistake somewhere, and am happy to discuss it (I'm reachable on the email listed on my github profile, maxminextrem@gmail.com, for example).

**Comment by gzorlee** [comment]
Thank you for the confirmation I read the proof few times and maybe it was my interpretation but I looked for the induction because of the n and m so I couldn't connect the dots. But under the light of both of your explanations I see clearly how you planned to proceed.

I will have another look and dig a bit deeper.

Once again very nice work for a very nice book!
